'use strict';

const _types = this._types = {
  COMPONENT_CREATED: 'COMPONENT_CREATED',
  COMPONENT_DELETED: 'COMPONENT_DELETED',
  COMPONENT_UPDATED: 'COMPONENT_UPDATED',
  HUMIDITY_PREFERENCES_CHANGED: 'HUMIDITY_PREFERENCES_CHANGED',
  HUMIDITY_STATE_CHANGED: 'HUMIDITY_STATE_CHANGED',
  NODE_DETAILS_CHANGED: 'NODE_DETAILS_CHANGED',
  NODE_STATE_CHANGED: 'NODE_STATE_CHANGED',
  NOTIFICATION: 'NOTIFICATION',
  PROXIMITY_PREFERENCES_CHANGE: 'PROXIMITY_PREFERENCES_CHANGE',
  PROXIMITY_STATE_CHANGED: 'PROXIMITY_STATE_CHANGED',
  RELAY_PREFERENCES_CHANGED: 'RELAY_PREFERENCES_CHANGED',
  RELAY_STATE_CHANGED: 'RELAY_STATE_CHANGED',
  TEMPERATURE_PREFERENCES_CHANGED: 'TEMPERATURE_PREFERENCES_CHANGED',
  TEMPERATURE_STATE_CHANGED: 'TEMPERATURE_STATE_CHANGED',
  TEMPHUM_PREFERENCES_CHANGED: 'TEMPHUM_PREFERENCES_CHANGED',
  TEMPHUM_STATE_CHANGED: 'TEMPHUM_STATE_CHANGED'
};

class EventMessageType {
  static get COMPONENT_CREATED() { return _types.COMPONENT_CREATED; }
  static get COMPONENT_DELETED() { return _types.COMPONENT_UPDATED; }
  static get COMPONENT_UPDATED() { return _types.COMPONENT_UPDATED; }
  static get HUMIDITY_PREFERENCES_CHANGED() { return _types.HUMIDITY_PREFERENCES_CHANGED; }
  static get HUMIDITY_STATE_CHANGED() { return _types.HUMIDITY_STATE_CHANGED; }
  static get NODE_DETAILS_CHANGED() { return _types.NODE_DETAILS_CHANGED; }
  static get NODE_STATE_CHANGED() { return _types.NODE_STATE_CHANGED; }
  static get NOTIFICATION() { return _types.NOTIFICATION }
  static get PROXIMITY_PREFERENCES_CHANGE() { return _types.PROXIMITY_PREFERENCES_CHANGE; }
  static get PROXIMITY_STATE_CHANGED() { return _types.PROXIMITY_STATE_CHANGED; }
  static get RELAY_PREFERENCES_CHANGED() { return _types.RELAY_PREFERENCES_CHANGED; }
  static get RELAY_STATE_CHANGED() { return _types.RELAY_STATE_CHANGED; }
  static get TEMPERATURE_PREFERENCES_CHANGED() { return _types.TEMPERATURE_PREFERENCES_CHANGED; }
  static get TEMPERATURE_STATE_CHANGED() { return _types.TEMPERATURE_STATE_CHANGED; }
  static get TEMPHUM_PREFERENCES_CHANGED() { return _types.TEMPHUM_PREFERENCES_CHANGED; }
  static get TEMPHUM_STATE_CHANGED() { return _types.TEMPHUM_STATE_CHANGED; }
}

module.exports = EventMessageType;
