export enum EventMessageType {
  COMPONENT_CREATED = <any>'COMPONENT_CREATED',
  COMPONENT_UPDATED = <any>'COMPONENT_UPDATED',
  COMPONENT_DELETED = <any>'COMPONENT_DELETED',
  HUMIDITY_PREFERENCES_CHANGED = <any>'HUMIDITY_PREFERENCES_CHANGED',
  HUMIDITY_STATE_CHANGED = <any>'HUMIDITY_STATE_CHANGED',
  NODE_STATE_CHANGED = <any>'NODE_STATE',
  NODE_DETAILS_CHANGED = <any>'NODE_DETAILS_CHANGE',
  NOTIFICATION = <any>'NOTIFICATION',
  PROXIMITY_PREFERENCES_CHANGED = <any>'PROXIMITY_PREFERENCES_CHANGED',
  PROXIMITY_STATE_CHANGED = <any>'PROXIMITY_STATE_CHANGED',
  RELAY_PREFERENCES_CHANGED = <any>'RELAY_PREFERENCES_CHANGED',
  RELAY_STATE_CHANGED = <any>'RELAY_STATE',
  TEMPERATURE_PREFERENCES_CHANGED = <any>'TEMPERATURE_PREFERENCES_CHANGED',
  TEMPERATURE_STATE_CHANGED = <any>'TEMPERATURE_STATE_CHANGED',
  TEMPHUM_PREFERENCES_CHANGED = <any>'TEMPHUM_PREFERENCES_CHANGED',
  TEMPHUM_STATE_CHANGED = <any>'TEMPHUM_STATE_CHANGED'
}
